title: MendelGeneDropping.jl
description: This package performs gene dropping with several useful options for the output.
google_analytics: 
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
